kind: Deployment
apiVersion: apps/v1
metadata:
  name: courie-driver-web-{{ .Values.versionName }}
  labels:
    app: courie-driver-web
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: courie-driver-web
  template:
    metadata:
      labels:
        app: courie-driver-web
        version: {{ .Values.version }}
      annotations:
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - name: courie-driver-web
          image: quay.io/jamjones/courie-driver-web:{{ default "latest" .Values.dockerTag }}
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - secretRef:
                name: courie-driver-web-directions-api-key
            - configMapRef:
                name: courie-driver-web
          imagePullPolicy: Always
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%