{{- if .Values.firstInstall -}}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: courie-driver-web-dr
spec:
  host: courie-driver-web
  subsets:
  - name: {{ .Values.versionName }}
    labels:
      version: {{ .Values.version }}
{{- end }}